SCANNED = 'SCANNED'
IN_CONTAINER = 'IN_CONTAINER'
COLLECTED = 'COLLECTED'
RECICLED = 'RECICLED'
TRACK_STATE_ID = {SCANNED: 1, IN_CONTAINER: 2, COLLECTED: 3, RECICLED: 4}

ORGANIC = 'ORGANIC'
PLASTIC = 'PLASTIC'
PAPER = 'PAPER'
REST = 'REST'
TRASH_TYPE_ID = {ORGANIC: 1, PLASTIC: 2, PAPER: 3, REST: 4}
