SCANNED = 'SCANNED'
CONTAINER = 'CONTAINER'
COLLECTED = 'COLLECTED'
RECYCLED = 'RECYCLED'
TRACK_STATE_ID = {SCANNED: 1, CONTAINER: 2, COLLECTED: 3, RECYCLED: 4}

ORGANIC = 'ORGANIC'
PLASTIC = 'PLASTIC'
PAPER = 'PAPER'
REST = 'REST'
GLASS = 'GLASS'
TRASH_TYPE_ID = {ORGANIC: 1, PLASTIC: 2, PAPER: 3, REST: 4, GLASS: 5}
