# Generated by Django 2.2.7 on 2019-11-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketCode', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TrackStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='tracks.Track')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
