# Generated by Django 2.2.7 on 2019-11-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20191130_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='trashType',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
