# Generated by Django 2.2.7 on 2019-11-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_trashtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
